FROM python:3.13
WORKDIR /streamlit

# Install the application dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy in the source code
COPY . .

CMD ["streamlit", "run", "streamlit_pages.py", "--server.port=8501", "--server.address=0.0.0.0"]